service: aws-container-lambda
framework Version: "3"
provider:
  name: aws
  lambdaHashingVersion: 20201221
  ecr:
    images:
      y1-test:
        path: ./
functions:
  hello:
    image:
      name: y1-test
      command:
        - app.handler