service: aws-container-lambda
framework Version: "3"
provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_REGION, 'us-east-1'}
  deploymentBucket:
    name: aw-lambda-deploy
  memorySize: 256
  ecr:
    images:
      aws-lambda-test:
        path: ./
functions:
  hello:
    image:
      name: aws-lambda-test
      command:
        - app.handler