service: publisher-report

plugins:
  - serverless-domain-manager
  - serverless-plugin-resource-tagging
  - serverless-offline
  - serverless-s3-local

useDotenv: true

provider:
  name: aws
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1
  memorySize: 512
  deploymentBucket:
    name: aw-lambda-quy-test-deploy
  stackName: ${self:service}-${self:provider.stage}
  stackTags:
    Billing Dept: test
    Role: ${self:service}
    Service: QTest
  versionFunctions: false
  environment:
    CHECK_SUM: ${env:CHECKSUM}
  apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:custom.config.${self:provider.stage}.rest_api_id}
    restApiRootResourceId:
      'Fn::ImportValue': ${self:custom.config.${self:provider.stage}.root_resource_id}

custom:
  defaultStage: dev
  customDomain:
    domainName: ${self:custom.config.${self:provider.stage}.domainName}
    basePath: ""
    stage: ${self:provider.stage}
    createRoute53Record: false
    endpointType: regional
    autoDomain: true
    autoDomainWaitFor: 120
  serverless-offline:
    address: localhost
  config:
    dev:
      logLevel: DEBUG
      domainName: development-report.test.com
      environment: development
      bucket: test-publisher-report-dev
      rest_api_id: 1111
      root_resource_id: 11111
    stg:
      logLevel: INFO
      domainName: development-report.test.com
      environment: staging
      bucket: test-publisher-report-stg
      rest_api_id: 222222
      root_resource_id: 22222
    prod:
      logLevel: INFO
      domainName: development-report.test.com
      environment: production
      bucket: test-publisher-report-report
      rest_api_id: 33333
      root_resource_id: 33333

functions:
  publisher_report:
    name: ${self:service}_${self:provider.stage}
    description: "[${self:provider.stage}] provider the publisher report"
    image:
      uri: 133398801298.dkr.ecr.ap-northeast-1.amazonaws.com/test-tools:${self:provider.environment.CHECK_SUM}
      command:
        - publisher/publisher-report.handler
    timeout: 5
    reservedConcurrency: 20
    events:
      - http:
          method: get
          path: /api/{proxy+}
          private: true
    tags:
      Environment: ${self:custom.config.${self:provider.stage}.environment}
