service: test-lambda-day-report
framework Version: "3"

plugins:
  - serverless-plugin-resource-tagging

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_REGION, 'us-east-1'}
  deploymentBucket:
    name: aw-lambda-test-deploy
  memorySize: 256
  stackName: ${self:service}-${self:provider.stage}
  environment:
    ENV: ${opt:stage, self:custom.defaultStage}

custom:
  defaultStage: dev
  functionName: quy-lambda-day-report
  config:
    dev:
      stage_formal: dev
    stg:
      stage_formal: staging

functions:
  day-report:
    name: ${self:custom.functionName}_${self:provider.stage}
    image:
      uri: 376206943201.dkr.ecr.us-east-1.amazonaws.com/test-tools/test-lambda:latest
      command:
        - day-report/day-app-report.day_handler
