service: test-lambda-month-report
framework Version: "3"

useDotenv: true

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_REGION, 'ap-northeast-1'}
  deploymentBucket:
    name: aw-lambda-test-deploy
  memorySize: 256
  stackName: test-lambda-month-report-${self:provider.stage}
  environment:
    ENV: ${opt:stage, self:custom.defaultStage}
    CHECK_SUM: ${env:CHECKSUM}

custom:
  defaultStage: dev
  functionName: quy-lambda-month-report
  config:
    dev:
      stage_formal: dev
    stg:
      stage_formal: staging

functions:
  day-report:
    name: ${self:custom.functionName}_${self:provider.stage}
    image:
      uri: 133398801298.dkr.ecr.ap-northeast-1.amazonaws.com/test-tools:${self:provider.environment.CHECK_SUM}
      command:
        - month-report/month-app-report.handler
