service: test-lambda-month-report
framework Version: "3"
provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_REGION, 'us-east-1'}
  deploymentBucket:
    name: aw-lambda-test-deploy
  memorySize: 256
  stackName: test-lambda-${self:provider.stage}
  environment:
    ENV: ${opt:stage, self:custom.defaultStage}
  ecr: #config upload ECR
    images:
      aws-lambda-month:
        path: ./
custom:
  defaultStage: dev
  functionName: quy-lambda-month-report
  config:
    dev:
      stage_formal: dev
    stg:
      stage_formal: staging

functions:
  day-report:
    name: ${self:custom.functionName}_${self:provider.stage}
    image:
      name: aws-lambda-month
      command:
        - month-app-report.handler
      tags:
        Environment: dev